### ISSUE TITLE
[BUG] invalid quser when saving a new user with unusual character

### ISSUE THREAD

**Issue by qcoumes** [qcoumes/wimsapi#5]
While exploring where the issue PremierLangage/wims-lti#43, I notice that when saving a new `User` with a `quser` containing special character (apostrophe `'` in this case), WIMS will actually create the new user, but will modify the `quser` : 

```python
from wimsapi import Class, User

supervisor = User("supervisor", "lastname", "firstname", "password")
c = Class("myclass", "name", "institution", "email@email.com", "password", supervisor)
u = User("ap'ostrophe", "ap'ostrophe", "ap'ostrphe", "password")
c.additem(u)
# WIMS response : {'status': 'OK', 'code': 'TZZ337C7FK', 'job': 'adduser', 'message': 'user apostrophe correctly added', 'user_id': 'apostrophe'}

c.getitem(u.quser, User)
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/home/quentin.coumes/Git/wimsapi/wimsapi/wclass.py", line 374, in getitem
#     return cls.get(self, identifier)
#   File "/home/quentin.coumes/Git/wimsapi/wimsapi/user.py", line 218, in get
#    raise AdmRawError(user_info['message'])
# wimsapi.exceptions.AdmRawError: WIMS' server responded with an ERROR: user ap'ostrophe not in this class (2344256)

c.getitem("apostrophe", User)
# <wimsapi.User object at 0x7f97ab0fcc10 - quser : apostrophe>
```

So WIMS basically changed the `quser` from `ap'ostrpohe` to `apostrpohe`, but `wimsapi` does not take this into account.

**Comment by qcoumes** [comment]
Fixed in deef74e405f2a7f0de2e033810f068f221fc14dc, implemented in 0.5.10
